# Generated by Django 4.0.8 on 2023-02-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyshop',
            name='logo',
            field=models.ImageField(blank=True, default='pharmacist/user-default.png', null=True, upload_to='pharmacyshop/'),
        ),
    ]
